### ISSUE TITLE
gem 'rubocop' の導入

### ISSUE THREAD

**Issue by yoshiki105** [Pluspo/pluspo#13]
## 概要
- gem 'rubocop'を導入する
- gem 'rubocop-rails' を導入する
- `bundle exec rubocop` でrubocopが動作すればOK

## 注意点
- gemをインストールするgroupを確認すること！
- 設定ファイル生成コマンド

  ```bash
  # rubocopの設定ファイル生成
  bundle exec rubocop --auto-gen-config
  ```

- `.rubocop.yml`の例
  ```yml
  inherit_from: .rubocop_todo.yml
  
  require:
    - rubocop-rails
    - rubocop-rspec # 必要なら
    - rubocop-performance # 必要なら
  
  AllCops:
    TargetRubyVersion: 3.1.0
    TargetRailsVersion: 6.1.4.4
    Exclude:
      - node_modules/**/*
      - vendor/**/*
      - bin/*
      - db/migrate/*
      - db/schema.rb
  
  Metrics/AbcSize:
    Max: 65
  
  Metrics/ClassLength:
    Max: 160
  
  Metrics/CyclomaticComplexity:
    Max: 10
  
  Layout/LineLength:
    Max: 200
  
  Metrics/MethodLength:
    Max: 50
  
  Metrics/PerceivedComplexity:
    Max: 11
  
  Style/ClassAndModuleChildren:
    Enabled: false
  
  Style/Documentation:
    Enabled: false
  
  Style/GuardClause:
    Enabled: false
  
  # Use only ascii symbols in comments.
  Style/AsciiComments:
    Enabled: false
  
  Layout/EmptyLinesAroundAttributeAccessor:
    Enabled: true
  
  Layout/SpaceAroundMethodCallOperator:
    Enabled: true
  
  Lint/RaiseException:
    Enabled: true
  
  Lint/StructNewOverride:
    Enabled: true
  
  Style/ExponentialNotation:
    Enabled: true
  
  Style/HashEachMethods:
    Enabled: false
  
  Style/HashTransformKeys:
    Enabled: true
  
  Style/HashTransformValues:
    Enabled: true
  
  Style/SlicingWithRange:
    Enabled: true
  
  Style/EmptyMethod:
    EnforcedStyle: expanded
  
  Rails/UnknownEnv:
    Environments:
      - production
      - staging
      - development
      - test
  
  Style/SymbolArray:
    Enabled: false
  
  Rails/LexicallyScopedActionFilter:
    Enabled: false
  
  Style/RescueStandardError:
    EnforcedStyle: implicit
  
  # RSpecを使う場合のみ
  RSpec/ExampleLength:
    Enabled: false
  
  RSpec/NestedGroups:
    Enabled: false
  ```

## 参考資料・スクショなど
[rubocop](https://github.com/rubocop/rubocop)
[rubocop-rails](https://github.com/rubocop/rubocop-rails)

## タスク
- [x] rubocopのインストール
- [x] rubocop-railsのインストール
- [x] rubocop設定ファイルの生成
- [x] `.rubocop.yml` の編集
- [ ] `.rubocop_todo.yml` の編集
